blank_issues_enabled: false
contact_links:
  - name: 🙌 Want to contribute?
    url: https://github.com/kiril6/termdeck/blob/master/CONTRIBUTING.md
    about: How to set up, pick a "good first issue", and open a PR.
